name: release
on:
  push:
    # tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
    #   - 'v*'
    branches:
      - main
    #   - dev
    # package.json 更改后再触发发布
    # paths: [ "package.json" ]
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.FRAMEWORK_CODE }}
          token: ${{ secrets.FRAMEWORK_ACCESS_TOKEN }}
          path: './framework'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MODULES_CODE }}
          token: ${{ secrets.MODULES_ACCESS_TOKEN }}
          path: './modules'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.VEIN_TALK_CODE }}
          token: ${{ secrets.VEIN_TALK_ACCESS_TOKEN }}
          # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: './code'  # 指定源码存放目录
          fetch-depth: 0 # 获取完整提交历史

      - name: Extract version and notes
        id: changelog
        run: |
          # 提取第一个版本号
          VERSION=$(awk '/^## \[v?[0-9]+\.[0-9]+\.[0-9]+]/ {print $2; exit}' code/CHANGELOG.md | tr -d '[]')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # 提取该版本的发布说明
          NOTES=$(awk -v version="$VERSION" '
            $0 ~ "## \\[" version "\\]" {flag=1; next}
            $0 ~ "## \\[" && flag {exit}
            flag {print}
          ' code/CHANGELOG.md)

          # 存储为多行输出
          delimiter="EOF_$(date +%s)"
          echo "notes<<$delimiter" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

      - name: Check release
        id: checkRelease
        run: |
          echo "version ${{ env.VERSION }}"
          echo "::set-output name=RELEASE_STATUS::$(curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/team-ide/VeinTalk/releases/tag/v${{ env.VERSION }})"
 
      - name: Install Node and NPM
        if: ${{ steps.checkRelease.outputs.RELEASE_STATUS == 404 }}
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Set up QEMU
        if: ${{ steps.checkRelease.outputs.RELEASE_STATUS == 404 }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        if: ${{ steps.checkRelease.outputs.RELEASE_STATUS == 404 }}
        uses: docker/setup-buildx-action@v1

      - run: |
          mkdir -p code/release/html
          mkdir -p code/release/hub-amd64
          mkdir -p code/release/im-amd64
          mkdir -p code/release/sdk-amd64
          mkdir -p code/release/hub-arm64
          mkdir -p code/release/im-arm64
          mkdir -p code/release/sdk-arm64
      - run: |
          ls
          chmod +x code/cmd/build/build-html.sh
          ./code/cmd/build/build-html.sh

      - name: Pull linux-amd64
        run: docker pull --platform linux/amd64 teamide/build-golang:amd64-1.24.6

      - name: Build linux-amd64
        run: |
          ls
          chmod +x code/cmd/build-amd64.sh
          docker run --platform linux/amd64 -v $(pwd):/build teamide/build-golang:amd64-1.24.6 /bin/sh /build/code/cmd/build/build-amd64.sh

      - name: Pull linux-arm64
        run: docker pull --platform linux/arm64 teamide/build-golang:arm64-1.24.6

      - name: Build linux-arm64
        run: |
          ls
          chmod +x code/cmd/build-arm64.sh
          docker run --platform linux/arm64 -v $(pwd):/build teamide/build-golang:arm64-1.24.6 /bin/sh /build/code/cmd/build/build-arm64.sh

      - run: |
          mv code/release release
          ls release
          mv release/hub-amd64 hub-amd64-${{env.VERSION}}
          zip -q -r hub-amd64-${{env.VERSION}}.zip hub-amd64-${{env.VERSION}}
          mv release/hub-arm64 hub-arm64-${{env.VERSION}}
          zip -q -r hub-arm64-${{env.VERSION}}.zip hub-arm64-${{env.VERSION}}
          ls

      - name: Create Release
        id: create_release
        if: ${{ steps.checkRelease.outputs.RELEASE_STATUS == 404 }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.notes }}
          draft: true # 是否是草稿
          prerelease: false # 是否是预发布


      # 上传 到 Release
      - if: ${{ steps.checkRelease.outputs.RELEASE_STATUS == 404 }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hub-amd64-${{env.VERSION}}.zip
          asset_name: hub-amd64-${{env.VERSION}}.zip # 上传后的文件名
          asset_content_type: application/zip
      - if: ${{ steps.checkRelease.outputs.RELEASE_STATUS == 404 }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hub-arm64-${{env.VERSION}}.zip
          asset_name: hub-arm64-${{env.VERSION}}.zip # 上传后的文件名
          asset_content_type: application/zip