name: release
on:
  push:
    # tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
    #   - 'v*'
    branches:
      - main
    #   - dev
    # package.json 更改后再触发发布
    # paths: [ "package.json" ]
jobs:
  code:
    runs-on: ubuntu-20.04
    steps:
      # 下载源码
      - uses: actions/checkout@v4
        with:
          repository: 'VeinTalk/VeinTalkCode'
          token: ${{ secrets.VEIN_TALK_ACCESS_TOKEN }}
          # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - run: |
          ls ./ -l
